In [1]:
import pandas as pd

In [2]:
fortune =pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby(by = "Sector")

In [3]:
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [4]:
type(fortune)

pandas.core.frame.DataFrame

In [5]:
type(sectors)

pandas.core.groupby.groupby.DataFrameGroupBy

# both are completly different objects or two different data frames

# THE .GROUPBY() METHOD

In [6]:
fortune =pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby(by = "Sector")
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [7]:
len(sectors)

21

In [8]:
fortune["Sector"].nunique()

21

# to see the unique groupings in the sectors

In [9]:
sectors.size()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [10]:
fortune["Sector"].value_counts()

Financials                      139
Energy                          122
Technology                      102
Retailing                        80
Health Care                      75
Business Services                51
Industrials                      46
Food, Beverages & Tobacco        43
Materials                        43
Wholesalers                      40
Transportation                   36
Chemicals                        30
Household Products               28
Engineering & Construction       26
Hotels, Resturants & Leisure     25
Media                            25
Motor Vehicles & Parts           24
Aerospace & Defense              20
Apparel                          15
Telecommunications               15
Food and Drug Stores             15
Name: Sector, dtype: int64

# to see the very first occurence of each and every unique value in the data frame groupby object SECTORS

In [11]:
fortune.head(3)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000

# for example: you can scroll down sectors list and see that walmart was the first occurence in the retailing sector

In [12]:
sectors.first()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,"Chicago, IL",96114,5176,161400
Apparel,Nike,Apparel,"Beaverton, OR",30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,"Milwaukee, WI",19330,419,27000
Chemicals,Dow Chemical,Chemicals,"Midland, MI",48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,"Irving, TX",246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction","Irving, TX",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,"Chicago, IL",67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,"Oak Brook, IL",25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
Industrials,General Electric,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
Materials,Alcoa,Metals,"New York, NY",22534,-322,60000
Media,Disney,Entertainment,"Burbank, CA",52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
Retailing,Walmart,General Merchandisers,"Bentonville, AR",482130,14694,2300000
Technology,Apple,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
Telecommunications,AT&T,Telecommunications,"Dallas, TX",146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [13]:
fortune.tail()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
996,New York Community Bancorp,Financials,Commercial Banks,"Westbury, NY",1902,-47,3448
997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
999,Wendy’s,"Hotels, Resturants & Leisure",Food Services,"Dublin, OH",1896,161,21200
1000,Briggs & Stratton,Industrials,Industrial Machinery,"Wauwatosa, WI",1895,46,5480

In [14]:
sectors.last()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Delta Tucker Holdings,Aerospace and Defense,"McLean, VA",1923,-133,12000
Apparel,Guess,Apparel,"Los Angeles, CA",2204,82,13500
Business Services,DeVry Education Group,Education,"Downers Grove, IL",1910,140,11770
Chemicals,H.B. Fuller,Chemicals,"St. Paul, MN",2084,87,4425
Energy,Portland General Electric,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
Engineering & Construction,MDC Holdings,Homebuilders,"Denver, CO",1909,66,1225
Financials,New York Community Bancorp,Commercial Banks,"Westbury, NY",1902,-47,3448
Food and Drug Stores,Fred’s,Food and Drug Stores,"Memphis, TN",2151,-7,7103
"Food, Beverages & Tobacco",Alliance One International,Tobacco,"Morrisville, NC",2066,-15,6835
Health Care,Providence Service,Health Care: Pharmacy and Other Services,"Tucson, AZ",1987,84,9072
"Hotels, Resturants & Leisure",Wendy’s,Food Services,"Dublin, OH",1896,161,21200
Household Products,Revlon,Household and Personal Products,"New York, NY",1914,56,5700
Industrials,Briggs & Stratton,Industrial Machinery,"Wauwatosa, WI",1895,46,5480
Materials,Schnitzer Steel Industries,Metals,"Portland, OR",1924,-197,2955
Media,Cenveo,"Publishing, Printing","Stamford, CT",1921,-31,7300
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,"Indianaoplis, IN",1986,182,2700
Retailing,99 Cents Only Stores,Specialty Retailers: Other,"Commerce, CA",1999,-232,18200
Technology,F5 Networks,Network and Other Communications Equipment,"Seattle, WA",1920,365,4178
Telecommunications,Equinix,Telecommunications,"Redwood City, CA",2726,188,5042
Transportation,Roadrunner Transportation Systems,Transportation and Logistics,"Cudahy, WI",1995,48,4502
Wholesalers,BlueLinx Holdings,Wholesalers: Diversified,"Atlanta, GA",1917,-12,1600

# you can see that in the industrial sector Briggs AND stratton was the last one in the tail method in the above data frame

# GROUPING THE DATA BY EACH AND EVERY GROUP AND WHAT FALLS UNDER EACH CATEGORY

# FOR EXAMPLE: IT WILL SHOW EACH AND EVERY ROW THAT FALLS UNDER APPARELS CATEGORY

# GROUPS ATTRIBUTE IS GIVING ME A DICTIONARY

In [15]:
fortune.loc[24]

Company                     Boeing
Sector         Aerospace & Defense
Industry     Aerospace and Defense
Location               Chicago, IL
Revenue                      96114
Profits                       5176
Employees                   161400
Name: 24, dtype: object

# you can see above index 24 falls in sector Aerospace & Defense

In [16]:
sectors.groups

{'Aerospace & Defense': Int64Index([ 24,  45,  60,  88, 118, 120, 209, 245, 282, 378, 389, 490, 560,
             605, 785, 788, 836, 903, 958, 987],
            dtype='int64', name='Rank'),
 'Apparel': Int64Index([91, 231, 340, 354, 448, 547, 575, 597, 683, 695, 726, 794, 877,
             882, 917],
            dtype='int64', name='Rank'),
 'Business Services': Int64Index([144, 186, 199, 204, 221, 248, 249, 294, 307, 312, 355, 392, 404,
             440, 467, 468, 481, 485, 492, 503, 545, 626, 635, 652, 677, 694,
             714, 729, 734, 735, 737, 744, 767, 776, 777, 783, 791, 792, 796,
             801, 803, 816, 819, 820, 869, 870, 886, 939, 951, 952, 993],
            dtype='int64', name='Rank'),
 'Chemicals': Int64Index([ 56, 101, 182, 189, 206, 253, 262, 277, 288, 296, 316, 538, 549,
             555, 566, 580, 613, 624, 654, 668, 717, 720, 724, 758, 761, 829,
             865, 898, 934, 949],
            dtype='int64', name='Rank'),
 'Energy': Int64Index([  2,  14,  30,  32,  42,  65,  90,  95,  98, 104,
             ...
             953, 955, 962, 966, 980, 981, 983, 995, 997, 997],
            dtype='int64', name='Rank', length=122),
 'Engineering & Construction': Int64Index([155, 156, 235, 260, 301, 314, 352, 381, 433, 478, 498, 501, 516,
             572, 576, 640, 719, 738, 822, 863, 874, 892, 929, 963, 985, 994],
            dtype='int64', name='Rank'),
 'Financials': Int64Index([  4,  16,  23,  26,  27,  29,  35,  40,  43,  49,
             ...
             920, 923, 925, 926, 936, 938, 959, 976, 988, 996],
            dtype='int64', name='Rank', length=139),
 'Food and Drug Stores': Int64Index([7, 17, 19, 87, 107, 160, 181, 595, 614, 631, 669, 756, 809, 849,
             928],
            dtype='int64', name='Rank'),
 'Food, Beverages & Tobacco': Int64Index([ 41,  44,  62,  66,  84,  94, 106, 149, 153, 161, 176, 207, 215,
             242, 266, 304, 336, 337, 362, 397, 413, 429, 452, 456, 460, 535,
             542, 567, 574, 587, 608, 615, 636, 664, 686, 702, 770, 787, 795,
             804, 889, 902, 954],
            dtype='int64', name='Rank'),
 'Health Care': Int64Index([  5,   6,  12,  21,  22,  33,  39,  46,  52,  55,  63,  72,  79,
              86, 123, 124, 125, 130, 138, 140, 141, 168, 172, 200, 201, 202,
             263, 268, 278, 286, 287, 290, 291, 305, 325, 358, 359, 372, 420,
             430, 431, 447, 457, 465, 469, 515, 527, 537, 553, 559, 583, 618,
             629, 661, 684, 693, 697, 708, 746, 749, 766, 775, 790, 799, 815,
             818, 845, 868, 881, 883, 935, 960, 965, 977, 978],
            dtype='int64', name='Rank'),
 'Hotels, Resturants & Leisure': Int64Index([109, 146, 195, 218, 241, 254, 309, 371, 444, 466, 534, 546, 557,
             562, 585, 731, 763, 764, 779, 797, 895, 915, 918, 941, 999],
            dtype='int64', name='Rank'),
 'Household Products': Int64Index([ 34, 151, 174, 256, 261, 328, 338, 345, 370, 434, 441, 450, 455,
             533, 550, 554, 601, 665, 699, 716, 856, 890, 900, 907, 932, 950,
             967, 992],
            dtype='int64', name='Rank'),
 'Industrials': Int64Index([  11,   59,   75,   93,   97,  128,  134,  148,  211,  224,  360,
              377,  396,  412,  419,  539,  544,  596,  622,  623,  630,  645,
              655,  658,  666,  674,  690,  757,  782,  789,  806,  813,  823,
              831,  832,  835,  841,  847,  866,  867,  873,  887,  942,  947,
              964, 1000],
            dtype='int64', name='Rank'),
 'Materials': Int64Index([126, 127, 170, 244, 251, 303, 321, 341, 356, 373, 375, 383, 417,
             418, 426, 435, 446, 480, 489, 514, 518, 577, 586, 616, 617, 620,
             625, 628, 637, 639, 641, 660, 667, 687, 691, 751, 774, 793, 857,
             885, 911, 982, 986],
            dtype='int64', name='Rank'),
 'Media': Int64Index([ 53,  96,  99, 203, 213, 255, 327, 366, 406, 414, 525, 530, 681,
             705, 707, 722, 741, 752, 759, 762, 821, 913, 968, 969, 989],
            dtype='int64', name='Rank'),
 'Motor Vehicles & Parts': Int64Index([  8,   9,  70, 147, 154, 169, 281, 310, 334, 339, 424, 428, 470,
             588, 591, 604, 647, 670, 718, 739, 811, 957, 961, 979],
            dtype='int64', name='Rank'),
 'Retailing': Int64Index([  1,  15,  28,  38,  47,  71,  89, 103, 111, 132, 136, 139, 143,
             145, 177, 180, 191, 196, 197, 228, 234, 237, 238, 240, 258, 267,
             269, 280, 293, 297, 299, 302, 330, 342, 346, 361, 365, 374, 379,
             380, 393, 415, 427, 439, 495, 500, 502, 511, 512, 517, 523, 582,
             592, 602, 607, 610, 621, 643, 644, 648, 657, 675, 689, 721, 748,
             771, 773, 807, 812, 824, 825, 827, 840, 876, 894, 899, 922, 937,
             940, 973],
            dtype='int64', name='Rank'),
 'Technology': Int64Index([  3,  18,  20,  25,  31,  36,  51,  54,  77, 110,
             ...
             931, 943, 944, 946, 956, 970, 971, 975, 984, 990],
            dtype='int64', name='Rank', length=102),
 'Telecommunications': Int64Index([10, 13, 37, 116, 159, 187, 292, 333, 399, 443, 461, 496, 526, 619,
             786],
            dtype='int64', name='Rank'),
 'Transportation': Int64Index([ 48,  58,  67,  68,  80, 129, 142, 208, 239, 270, 353, 390, 395,
             405, 407, 416, 432, 459, 521, 528, 570, 578, 642, 672, 709, 713,
             740, 800, 814, 858, 884, 930, 933, 945, 972, 974],
            dtype='int64', name='Rank'),
 'Wholesalers': Int64Index([ 57,  64,  92, 102, 108, 119, 122, 167, 183, 185, 212, 276, 285,
             315, 317, 320, 323, 335, 351, 357, 369, 391, 423, 463, 474, 477,
             484, 564, 581, 599, 627, 653, 685, 727, 747, 780, 808, 837, 875,
             991],
            dtype='int64', name='Rank')}

In [17]:
fortune =pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby(by = "Sector")
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

# RETRIVE A GROUP WITH THE .GET_GROUP() METHOD

# this method is actually going to be called on the groupby object

# BELOW WE PULL OUT THAT GROUPING OF 21 AVAILABLE GROUPINGS FROM OUR GROUP BY OBJECT

In [18]:
sectors.get_group("Apparel")
sectors.get_group("Retailing")
sectors.get_group("Technology")

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
18,Amazon.com,Technology,Internet Services and Retailing,"Seattle, WA",107006,596,230800
20,HP,Technology,"Computers, Office Equipment","Palo Alto, CA",103355,4554,287000
25,Microsoft,Technology,Computer Software,"Redmond, WA",93580,12193,118000
31,IBM,Technology,Information Technology Services,"Armonk, NY",82461,13190,411798
36,Alphabet,Technology,Internet Services and Retailing,"Mountain View, CA",74989,16348,61814
51,Intel,Technology,Semiconductors and Other Electronic Components,"Santa Clara, CA",55355,11420,107300
54,Cisco Systems,Technology,Network and Other Communications Equipment,"San Jose, CA",49161,8981,71833
77,Oracle,Technology,Computer Software,"Redwood City, CA",38226,9938,132000
110,Qualcomm,Technology,Network and Other Communications Equipment,"San Diego, CA",25281,5271,33000
113,EMC,Technology,Computer Peripherals,"Hopkinton, MA",24704,1990,72000
133,Danaher,Technology,"Scientific,Photographic and Control Equipment","Washington, DC",20909,3357,81000
150,Xerox,Technology,Information Technology Services,"Norwalk, CT",18664,474,143600
157,Facebook,Technology,Internet Services and Retailing,"Menlo Park, CA",17928,3688,12691
158,Jabil Circuit,Technology,Semiconductors and Other Electronic Components,"St. Petersburg, FL",17914,284,161000
164,Thermo Fisher Scientific,Technology,"Scientific,Photographic and Control Equipment","Waltham, MA",16965,1975,52400
173,Micron Technology,Technology,Semiconductors and Other Electronic Components,"Boise, ID",16192,2899,31800
194,Western Digital,Technology,Computer Peripherals,"Irvine, CA",14572,1465,76449
219,Texas Instruments,Technology,Semiconductors and Other Electronic Components,"Dallas, TX",13000,2986,29977
220,CDW,Technology,Information Technology Services,"Lincolnshire, IL",12989,403,8465
230,Cognizant Technology Solutions,Technology,Information Technology Services,"Teaneck, NJ",12416,1624,221700
233,Computer Sciences,Technology,Information Technology Services,"Falls Church, VA",12183,-8,70000
284,Liberty Interactive,Technology,Internet Services and Retailing,"Englewood, CO",9989,869,22080
295,Applied Materials,Technology,Semiconductors and Other Electronic Components,"Santa Clara, CA",9659,1377,15050
300,eBay,Technology,Internet Services and Retailing,"San Jose, CA",9496,1725,11600
308,Priceline Group,Technology,Internet Services and Retailing,"Norwalk, CT",9224,2551,15500
313,Corning,Technology,Network and Other Communications Equipment,"Corning, NY",9111,1339,35700
331,Broadcom,Technology,Semiconductors and Other Electronic Components,"Irvine, CA",8394,978,9950
385,Expedia,Technology,Internet Services and Retailing,"Bellevue, WA",6672,765,18730
386,salesforce.com,Technology,Computer Software,"San Francisco, CA",6667,-47,19742
...,...,...,...,...,...,...,...
778,Diebold,Technology,"Computers, Office Equipment","North Canton, OH",2768,74,16000
805,Plexus,Technology,Semiconductors and Other Electronic Components,"Neenah, WI",2654,94,14000
830,Benchmark Electronics,Technology,Semiconductors and Other Electronic Components,"Angleton, TX",2541,95,10500
834,Teradata,Technology,Computer Software,"Dayton, OH",2530,-214,11300
842,Autodesk,Technology,Computer Software,"San Rafael, CA",2504,-331,9500
854,Ciena,Technology,Network and Other Communications Equipment,"Hanover, MD",2446,12,5345
864,Mettler-Toledo International,Technology,"Scientific,Photographic and Control Equipment","Columbus, OH",2395,353,13000
871,Xilinx,Technology,Semiconductors and Other Electronic Components,"San Jose, CA",2377,648,3451
888,Maxim Integrated Products,Technology,Semiconductors and Other Electronic Components,"San Jose, CA",2307,206,8250
891,Vishay Intertechnology,Technology,Semiconductors and Other Electronic Components,"Malvern, PA",2301,-109,22400
893,Teledyne Technologies,Technology,"Scientific,Photographic and Control Equipment","Thousand Oaks, CA",2298,196,9200
896,Trimble Navigation,Technology,"Scientific,Photographic and Control Equipment","Sunnyvale, CA",2290,121,8451
904,Brocade Communications Systems,Technology,Network and Other Communications Equipment,"San Jose, CA",2264,340,4640
905,PerkinElmer,Technology,"Scientific,Photographic and Control Equipment","Waltham, MA",2263,212,8000
906,Wayfair,Technology,Internet Services and Retailing,"Boston, MA",2250,-77,3809
909,Synopsys,Technology,Computer Software,"Mountain View, CA",2242,226,10284
912,Illumina,Technology,"Scientific,Photographic and Control Equipment","San Diego, CA",2220,462,4600
914,Twitter,Technology,Internet Services and Retailing,"San Francisco, CA",2218,-521,3898
919,Akamai Technologies,Technology,Computer Software,"Cambridge, MA",2197,321,6084
927,Gartner,Technology,Information Technology Services,"Stamford, CT",2163,176,7834
931,Microchip Technology,Technology,Semiconductors and Other Electronic Components,"Chandler, AZ",2147,369,9449
943,Maximus,Technology,Information Technology Services,"Reston, VA",2100,158,17000
944,TTM Technologies,Technology,Semiconductors and Other Electronic Components,"Costa Mesa, CA",2096,-26,29570
946,Engility Holdings,Technology,Information Technology Services,"Chantilly, VA",2086,-235,9800
956,Waters,Technology,"Scientific,Photographic and Control Equipment","Milford, MA",2042,469,6594
970,Rackspace Hosting,Technology,Internet Services and Retailing,"San Antonio, TX",2001,126,6189
971,VeriFone Systems,Technology,"Computers, Office Equipment","San Jose, CA",2001,79,5400
975,Super Micro Computer,Technology,"Computers, Office Equipment","San Jose, CA",1991,102,2285
984,Nuance Communications,Technology,Computer Software,"Burlington, MA",1931,-115,13500
990,F5 Networks,Technology,Network and Other Communications Equipment,"Seattle, WA",1920,365,4178

# in past you had to extract all 21 unique sectors one by one like the example below, however now you see get group is so effective

In [19]:
fortune[fortune["Sector"] == "Apparel"]

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
231,VF,Apparel,Apparel,"Greensboro, NC",12377,1232,64000
340,PVH,Apparel,Apparel,"New York, NY",8020,572,26200
354,Ralph Lauren,Apparel,Apparel,"New York, NY",7620,702,20000
448,Hanesbrands,Apparel,Apparel,"Winston-Salem, NC",5732,429,65300
547,Levi Strauss,Apparel,Apparel,"San Francisco, CA",4495,209,12500
575,Coach,Apparel,Apparel,"New York, NY",4192,402,12950
597,Under Armour,Apparel,Apparel,"Baltimore, MD",3963,233,9600
683,Fossil Group,Apparel,Apparel,"Richardson, TX",3229,221,15100
695,Skechers U.S.A.,Apparel,Apparel,"Manhattan Beach, CA",3159,232,6400
726,Carter’s,Apparel,Apparel,"Atlanta, GA",3014,238,16800
794,Wolverine World Wide,Apparel,Apparel,"Rockford, MI",2692,123,6550
877,G-III Apparel Group,Apparel,Apparel,"New York, NY",2344,114,8919
882,Columbia Sportswear,Apparel,Apparel,"Portland, OR",2326,174,5978
917,Guess,Apparel,Apparel,"Los Angeles, CA",2204,82,13500

# METHODS ON GROUP BY OBJECT AND DATA FRAME COLUMNS

In [20]:
fortune =pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby(by = "Sector")
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

# in min() you can see an ascending order - alphabetical alphabetically
# in max() it will be the descending order - alpahbetically

In [21]:
sectors.max()
sectors.min()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,B/E Aerospace,Aerospace and Defense,"Berwyn, PA",1923,-240,6955
Apparel,Carter’s,Apparel,"Atlanta, GA",2204,82,5978
Business Services,ABM Industries,"Advertising, marketing","Arlington, VA",1910,-1481,2400
Chemicals,A. Schulman,Chemicals,"Allentown, PA",2084,-816,1979
Energy,AES,Energy,"Akron, OH",1898,-23119,480
Engineering & Construction,AECOM,"Engineering, Construction","Atlanta, GA",1909,-155,1036
Financials,AIG,Commercial Banks,"Atlanta, GA",1902,-1194,187
Food and Drug Stores,CVS Health,Food and Drug Stores,"Austin, TX",2151,-62,1616
"Food, Beverages & Tobacco",Alliance One International,Beverages,"Arden Hills, MN",2066,-253,1857
Health Care,AbbVie,Health Care: Insurance and Managed Care,"Abbott Park, IL",1987,-458,2924
"Hotels, Resturants & Leisure",Bloomin’ Brands,Food Services,"Ann Arbor, MI",1896,-1394,8500
Household Products,Avon Products,"Home Equipment, Furnishings","Atlanta, GA",1914,-1149,4406
Industrials,3M,Construction and Farm Machinery,"Annapolis Junction, MD",1895,-6126,4104
Materials,A-Mark Precious Metals,"Building Materials, Glass","Atlanta, GA",1924,-1642,52
Media,AMC Networks,Entertainment,"Beverly Hills, CA",1921,-881,2341
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,"Akron, OH",1986,-889,2700
Retailing,99 Cents Only Stores,"Automotive Retailing, Services","Ankeny, IA",1999,-1243,2155
Technology,Activision Blizzard,Computer Peripherals,"Angleton, TX",1920,-4359,2285
Telecommunications,AT&T,Telecommunications,"Bethpage, NY",2726,-271,2700
Transportation,Alaska Air Group,Airlines,"Atlanta, GA",1995,-191,1223
Wholesalers,Airgas,Miscellaneous,"Atlanta, GA",1917,-502,500

# max and min show the last and first in alphabetical order in the groupingsm

In [22]:
sectors.get_group("Apparel")["Profits"].sum()

8236

# 8236 is the total profit below in apparel section

In [23]:
sectors.sum()

                              Revenue  Profits  Employees
Sector
Aerospace & Defense            357940    28742     968057
Apparel                         95968     8236     346397
Business Services              272195    28227    1361050
Chemicals                      243897    22628     463651
Energy                        1517809   -73447    1188927
Engineering & Construction     153983     5304     406708
Financials                    2217159   260209    3359948
Food and Drug Stores           483769    16759    1395398
Food, Beverages & Tobacco      555967    51417    1211632
Health Care                   1614707   106114    2678289
Hotels, Resturants & Leisure   169546    20697    2484245
Household Products             234737    14428     646038
Industrials                    497581    20764    1545229
Materials                      259145     4428     638123
Media                          220764    24347     550314
Motor Vehicles & Parts         482540    25898    1082560
Retailing                     1465076    47830    6227629
Technology                    1377600   180473    3578949
Telecommunications             461834    48637     832468
Transportation                 408508    44169    1536793
Wholesalers                    444800     8233     525597

In [24]:
sectors.mean()

                                   Revenue      Profits     Employees
Sector
Aerospace & Defense           17897.000000  1437.100000  48402.850000
Apparel                        6397.866667   549.066667  23093.133333
Business Services              5337.156863   553.470588  26687.254902
Chemicals                      8129.900000   754.266667  15455.033333
Energy                        12441.057377  -602.024590   9745.303279
Engineering & Construction     5922.423077   204.000000  15642.615385
Financials                    15950.784173  1872.007194  24172.287770
Food and Drug Stores          32251.266667  1117.266667  93026.533333
Food, Beverages & Tobacco     12929.465116  1195.744186  28177.488372
Health Care                   21529.426667  1414.853333  35710.520000
Hotels, Resturants & Leisure   6781.840000   827.880000  99369.800000
Household Products             8383.464286   515.285714  23072.785714
Industrials                   10816.978261   451.391304  33591.934783
Materials                      6026.627907   102.976744  14840.069767
Media                          8830.560000   973.880000  22012.560000
Motor Vehicles & Parts        20105.833333  1079.083333  45106.666667
Retailing                     18313.450000   597.875000  77845.362500
Technology                    13505.882353  1769.343137  35087.735294
Telecommunications            30788.933333  3242.466667  55497.866667
Transportation                11347.444444  1226.916667  42688.694444
Wholesalers                   11120.000000   205.825000  13139.925000

# to just focus on one aspect like revenue you can code like this below- by using the orginal name of the column from our orginal data frame

In [25]:
sectors["Revenue"].sum()

Sector
Aerospace & Defense              357940
Apparel                           95968
Business Services                272195
Chemicals                        243897
Energy                          1517809
Engineering & Construction       153983
Financials                      2217159
Food and Drug Stores             483769
Food, Beverages & Tobacco        555967
Health Care                     1614707
Hotels, Resturants & Leisure     169546
Household Products               234737
Industrials                      497581
Materials                        259145
Media                            220764
Motor Vehicles & Parts           482540
Retailing                       1465076
Technology                      1377600
Telecommunications               461834
Transportation                   408508
Wholesalers                      444800
Name: Revenue, dtype: int64

In [26]:
sectors["Profits"].max()

Sector
Aerospace & Defense              7608
Apparel                          3273
Business Services                6328
Chemicals                        7685
Energy                          16150
Engineering & Construction        803
Financials                      24442
Food and Drug Stores             5237
Food, Beverages & Tobacco        7351
Health Care                     18108
Hotels, Resturants & Leisure     5920
Household Products               7036
Industrials                      4833
Materials                         991
Media                            8382
Motor Vehicles & Parts           9687
Retailing                       14694
Technology                      53394
Telecommunications              17879
Transportation                   7610
Wholesalers                      1472
Name: Profits, dtype: int64

In [27]:
sectors["Employees"].sum()

Sector
Aerospace & Defense              968057
Apparel                          346397
Business Services               1361050
Chemicals                        463651
Energy                          1188927
Engineering & Construction       406708
Financials                      3359948
Food and Drug Stores            1395398
Food, Beverages & Tobacco       1211632
Health Care                     2678289
Hotels, Resturants & Leisure    2484245
Household Products               646038
Industrials                     1545229
Materials                        638123
Media                            550314
Motor Vehicles & Parts          1082560
Retailing                       6227629
Technology                      3578949
Telecommunications               832468
Transportation                  1536793
Wholesalers                      525597
Name: Employees, dtype: int64

In [28]:
sectors["Profits"].min()

Sector
Aerospace & Defense              -240
Apparel                            82
Business Services               -1481
Chemicals                        -816
Energy                         -23119
Engineering & Construction       -155
Financials                      -1194
Food and Drug Stores              -62
Food, Beverages & Tobacco        -253
Health Care                      -458
Hotels, Resturants & Leisure    -1394
Household Products              -1149
Industrials                     -6126
Materials                       -1642
Media                            -881
Motor Vehicles & Parts           -889
Retailing                       -1243
Technology                      -4359
Telecommunications               -271
Transportation                   -191
Wholesalers                      -502
Name: Profits, dtype: int64

In [29]:
sectors["Employees"].mean()

Sector
Aerospace & Defense             48402.850000
Apparel                         23093.133333
Business Services               26687.254902
Chemicals                       15455.033333
Energy                           9745.303279
Engineering & Construction      15642.615385
Financials                      24172.287770
Food and Drug Stores            93026.533333
Food, Beverages & Tobacco       28177.488372
Health Care                     35710.520000
Hotels, Resturants & Leisure    99369.800000
Household Products              23072.785714
Industrials                     33591.934783
Materials                       14840.069767
Media                           22012.560000
Motor Vehicles & Parts          45106.666667
Retailing                       77845.362500
Technology                      35087.735294
Telecommunications              55497.866667
Transportation                  42688.694444
Wholesalers                     13139.925000
Name: Employees, dtype: float64

# to take out revenue and profit, we use a square bracket to extract and the other square bracket to put the list inside

# we have sectors or grouping represented as index labels

In [30]:
sectors[["Revenue","Profits"]].sum()

                              Revenue  Profits
Sector
Aerospace & Defense            357940    28742
Apparel                         95968     8236
Business Services              272195    28227
Chemicals                      243897    22628
Energy                        1517809   -73447
Engineering & Construction     153983     5304
Financials                    2217159   260209
Food and Drug Stores           483769    16759
Food, Beverages & Tobacco      555967    51417
Health Care                   1614707   106114
Hotels, Resturants & Leisure   169546    20697
Household Products             234737    14428
Industrials                    497581    20764
Materials                      259145     4428
Media                          220764    24347
Motor Vehicles & Parts         482540    25898
Retailing                     1465076    47830
Technology                    1377600   180473
Telecommunications             461834    48637
Transportation                 408508    44169
Wholesalers                    444800     8233

In [14]:
fortune =pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby(by = ["Sector","Industry"])
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

# GROUPING BY MULTIPLE COLUMNS

In [15]:
sectors.size()

Sector                      Industry
Aerospace & Defense         Aerospace and Defense                             20
Apparel                     Apparel                                           15
Business Services           Advertising, marketing                             2
                            Diversified Outsourcing Services                  14
                            Education                                          3
                            Financial Data Services                           19
                            Miscellaneous                                      3
                            Temporary Help                                     5
                            Waste Management                                   5
Chemicals                   Chemicals                                         30
Energy                      Energy                                            14
                            Mining, Crude-Oil Production                      28
                            Miscellaneous                                      1
                            Oil and Gas Equipment, Services                    9
                            Petroleum Refining                                17
                            Pipelines                                         12
                            Utilities: Gas and Electric                       41
Engineering & Construction  Engineering, Construction                         14
                            Homebuilders                                      12
Financials                  Commercial Banks                                  28
                            Diversified Financials                            15
                            Insurance: Life, Health (Mutual)                  10
                            Insurance: Life, Health (stock)                   18
                            Insurance: Property and Casualty (Mutual)          7
                            Insurance: Property and Casualty (Stock)          28
                            Real estate                                       15
                            Securities                                        18
Food and Drug Stores        Food and Drug Stores                              15
Food, Beverages & Tobacco   Beverages                                          9
                            Food Consumer Products                            20
                                                                              ..
Materials                   Metals                                            14
                            Miscellaneous                                      1
                            Packaging, Containers                             16
Media                       Entertainment                                     18
                            Publishing, Printing                               7
Motor Vehicles & Parts      Motor Vehicles and Parts                          24
Retailing                   Automotive Retailing, Services                    10
                            General Merchandisers                             10
                            Specialty Retailers: Apparel                      18
                            Specialty Retailers: Other                        42
Technology                  Computer Peripherals                               4
                            Computer Software                                 14
                            Computers, Office Equipment                        7
                            Information Technology Services                   13
                            Internet Services and Retailing                   15
                            Network and Other Communications Equipment        14
                            Scientific,Photographic and Control Equipment     12
                            Semiconductors and Other Electronic Components    23
Telecommunications          Telecommunications                                15
Transportation              Airlines                                           9
                            Mail, Package, and Freight Delivery                2
                            Miscellaneous                                      1
                            Railroads                                          5
                            Transportation Equipment                           5
                            Transportation and Logistics                       5
                            Trucking, Truck Leasing                            9
Wholesalers                 Miscellaneous                                      1
                            Wholesalers: Diversified                          25
                            Wholesalers: Electronics and Office Equipment      8
                            Wholesalers: Food and Grocery                      6
Length: 79, dtype: int64

# below we have sector and industry both as we grouped them above

In [16]:
sectors.sum()

                                                                           Revenue  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            357940
Apparel                    Apparel                                           95968
Business Services          Advertising, marketing                            22748
                           Diversified Outsourcing Services                  64829
                           Education                                          7485
                           Financial Data Services                          100778
                           Miscellaneous                                     11185
                           Temporary Help                                    34716
                           Waste Management                                  30454
Chemicals                  Chemicals                                        243897
Energy                     Energy                                            67749
                           Mining, Crude-Oil Production                     176435
                           Miscellaneous                                      3159
                           Oil and Gas Equipment, Services                   82827
                           Petroleum Refining                               705472
                           Pipelines                                        138756
                           Utilities: Gas and Electric                      343411
Engineering & Construction Engineering, Construction                         99774
                           Homebuilders                                      54209
Financials                 Commercial Banks                                 623669
                           Diversified Financials                           327075
                           Insurance: Life, Health (Mutual)                 181336
                           Insurance: Life, Health (stock)                  245551
                           Insurance: Property and Casualty (Mutual)        143682
                           Insurance: Property and Casualty (Stock)         548027
                           Real estate                                       62748
                           Securities                                        85071
Food and Drug Stores       Food and Drug Stores                             483769
Food, Beverages & Tobacco  Beverages                                         79396
                           Food Consumer Products                           238954
...                                                                            ...
Materials                  Metals                                            99925
                           Miscellaneous                                      6070
                           Packaging, Containers                            105965
Media                      Entertainment                                    186276
                           Publishing, Printing                              34488
Motor Vehicles & Parts     Motor Vehicles and Parts                         482540
Retailing                  Automotive Retailing, Services                   113823
                           General Merchandisers                            684320
                           Specialty Retailers: Apparel                     122975
                           Specialty Retailers: Other                       543958
Technology                 Computer Peripherals                              48950
                           Computer Software                                179112
                           Computers, Office Equipment                      353781
                           Information Technology Services                  166067
                           Internet Services and Retailing                  259136
                           Network and Other Communications Equipment       125697
                           Scientific,Photographic and Control Equipment     65832
                           Semiconductors and Other Electronic Components   179025
Telecommunications         Telecommunications                               461834
Transportation             Airlines                                         158948
                           Mail, Package, and Freight Delivery              105816
                           Miscellaneous                                      2148
                           Railroads                                         48554
                           Transportation Equipment                          23855
                           Transportation and Logistics                      33237
                           Trucking, Truck Leasing                           35950
Wholesalers                Miscellaneous                                      8982
                           Wholesalers: Diversified                         176138
                           Wholesalers: Electronics and Office Equipment    147906
                           Wholesalers: Food and Grocery                    111774

                                                                           Profits  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                             28742
Apparel                    Apparel                                            8236
Business Services          Advertising, marketing                             1549
                           Diversified Outsourcing Services                   4305
                           Education                                            69
                           Financial Data Services                           17456
                           Miscellaneous                                      2130
                           Temporary Help                                     1000
                           Waste Management                                   1718
Chemicals                  Chemicals                                         22628
Energy                     Energy                                           -13038
                           Mining, Crude-Oil Production                    -124555
                           Miscellaneous                                       476
                           Oil and Gas Equipment, Services                   -4047
                           Petroleum Refining                                31888
                           Pipelines                                          5814
                           Utilities: Gas and Electric                       30015
Engineering & Construction Engineering, Construction                          1765
                           Homebuilders                                       3539
Financials                 Commercial Banks                                 129760
                           Diversified Financials                            28548
                           Insurance: Life, Health (Mutual)                   5601
                           Insurance: Life, Health (stock)                   19731
                           Insurance: Property and Casualty (Mutual)          8031
                           Insurance: Property and Casualty (Stock)          44803
                           Real estate                                        9480
                           Securities                                        14255
Food and Drug Stores       Food and Drug Stores                              16759
Food, Beverages & Tobacco  Beverages                                         11698
                           Food Consumer Products                            19263
...                                                                            ...
Materials                  Metals                                            -2241
                           Miscellaneous                                         7
                           Packaging, Containers                              4445
Media                      Entertainment                                     25686
                           Publishing, Printing                              -1339
Motor Vehicles & Parts     Motor Vehicles and Parts                          25898
Retailing                  Automotive Retailing, Services                     2550
                           General Merchandisers                             20137
                           Specialty Retailers: Apparel                       4583
                           Specialty Retailers: Other                        20560
Technology                 Computer Peripherals                               3975
                           Computer Software                                 26457
                           Computers, Office Equipment                       58433
                           Information Technology Services                   16402
                           Internet Services and Retailing                   22232
                           Network and Other Communications Equipment        18907
                           Scientific,Photographic and Control Equipment      9346
                           Semiconductors and Other Electronic Components    24721
Telecommunications         Telecommunications                                48637
Transportation             Airlines                                          23800
                           Mail, Package, and Freight Delivery                5894
                           Miscellaneous                                       227
                           Railroads                                          9005
                           Transportation Equipment                           2438
                           Transportation and Logistics                        895
                           Trucking, Truck Leasing                            1910
Wholesalers                Miscellaneous                                        17
                           Wholesalers: Diversified                           5193
                           Wholesalers: Electronics and Office Equipment      1857
                           Wholesalers: Food and Grocery                      1166

                                                                           Employees
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                              968057
Apparel                    Apparel                                            346397
Business Services          Advertising, marketing                             124100
                           Diversified Outsourcing Services                   708330
                           Education                                           46755
                           Financial Data Services                            264926
                           Miscellaneous                                       37720
                           Temporary Help                                      60020
                           Waste Management                                   119199
Chemicals                  Chemicals                                          463651
Energy                     Energy                                              70072
                           Mining, Crude-Oil Production                       149110
                           Miscellaneous                                        6700
                           Oil and Gas Equipment, Services                    225795
                           Petroleum Refining                                 244880
                           Pipelines                                           72141
                           Utilities: Gas and Electric                        420229
Engineering & Construction Engineering, Construction                          368104
                           Homebuilders                                        38604
Financials                 Commercial Banks                                  1539024
                           Diversified Financials                             329114
                           Insurance: Life, Health (Mutual)                    58801
                           Insurance: Life, Health (stock)                    202233
                           Insurance: Property and Casualty (Mutual)          133148
                           Insurance: Property and Casualty (Stock)           794123
                           Real estate                                        160579
                           Securities                                         142926
Food and Drug Stores       Food and Drug Stores                              1395398
Food, Beverages & Tobacco  Beverages                                          199107
                           Food Consumer Products                             665439
...                                                                              ...
Materials                  Metals                                             193559
                           Miscellaneous                                          52
                           Packaging, Containers                              333446
Media                      Entertainment                                      383564
                           Publishing, Printing                               166750
Motor Vehicles & Parts     Motor Vehicles and Parts                          1082560
Retailing                  Automotive Retailing, Services                     174974
                           General Merchandisers                             3408100
                           Specialty Retailers: Apparel                       770543
                           Specialty Retailers: Other                        1874012
Technology                 Computer Peripherals                               175259
                           Computer Software                                  388796
                           Computers, Office Equipment                        468085
                           Information Technology Services                    985639
                           Internet Services and Retailing                    430855
                           Network and Other Communications Equipment         299310
                           Scientific,Photographic and Control Equipment      231501
                           Semiconductors and Other Electronic Components     599504
Telecommunications         Telecommunications                                 832468
Transportation             Airlines                                           391601
                           Mail, Package, and Freight Delivery                664275
                           Miscellaneous                                        4200
                           Railroads                                          121844
                           Transportation Equipment                            59726
                           Transportation and Logistics                       124691
                           Trucking, Truck Leasing                            170456
Wholesalers                Miscellaneous                                        9200
                           Wholesalers: Diversified                           233831
                           Wholesalers: Electronics and Office Equipment      166661
                           Wholesalers: Food and Grocery                      115905

[79 rows x 3 columns]

In [17]:
sectors["Revenue"].sum()

Sector                      Industry
Aerospace & Defense         Aerospace and Defense                             357940
Apparel                     Apparel                                            95968
Business Services           Advertising, marketing                             22748
                            Diversified Outsourcing Services                   64829
                            Education                                           7485
                            Financial Data Services                           100778
                            Miscellaneous                                      11185
                            Temporary Help                                     34716
                            Waste Management                                   30454
Chemicals                   Chemicals                                         243897
Energy                      Energy                                             67749
                            Mining, Crude-Oil Production                      176435
                            Miscellaneous                                       3159
                            Oil and Gas Equipment, Services                    82827
                            Petroleum Refining                                705472
                            Pipelines                                         138756
                            Utilities: Gas and Electric                       343411
Engineering & Construction  Engineering, Construction                          99774
                            Homebuilders                                       54209
Financials                  Commercial Banks                                  623669
                            Diversified Financials                            327075
                            Insurance: Life, Health (Mutual)                  181336
                            Insurance: Life, Health (stock)                   245551
                            Insurance: Property and Casualty (Mutual)         143682
                            Insurance: Property and Casualty (Stock)          548027
                            Real estate                                        62748
                            Securities                                         85071
Food and Drug Stores        Food and Drug Stores                              483769
Food, Beverages & Tobacco   Beverages                                          79396
                            Food Consumer Products                            238954
                                                                               ...
Materials                   Metals                                             99925
                            Miscellaneous                                       6070
                            Packaging, Containers                             105965
Media                       Entertainment                                     186276
                            Publishing, Printing                               34488
Motor Vehicles & Parts      Motor Vehicles and Parts                          482540
Retailing                   Automotive Retailing, Services                    113823
                            General Merchandisers                             684320
                            Specialty Retailers: Apparel                      122975
                            Specialty Retailers: Other                        543958
Technology                  Computer Peripherals                               48950
                            Computer Software                                 179112
                            Computers, Office Equipment                       353781
                            Information Technology Services                   166067
                            Internet Services and Retailing                   259136
                            Network and Other Communications Equipment        125697
                            Scientific,Photographic and Control Equipment      65832
                            Semiconductors and Other Electronic Components    179025
Telecommunications          Telecommunications                                461834
Transportation              Airlines                                          158948
                            Mail, Package, and Freight Delivery               105816
                            Miscellaneous                                       2148
                            Railroads                                          48554
                            Transportation Equipment                           23855
                            Transportation and Logistics                       33237
                            Trucking, Truck Leasing                            35950
Wholesalers                 Miscellaneous                                       8982
                            Wholesalers: Diversified                          176138
                            Wholesalers: Electronics and Office Equipment     147906
                            Wholesalers: Food and Grocery                     111774
Name: Revenue, Length: 79, dtype: int64

In [18]:
sectors["Employees"].mean()

Sector                      Industry
Aerospace & Defense         Aerospace and Defense                              48402.850000
Apparel                     Apparel                                            23093.133333
Business Services           Advertising, marketing                             62050.000000
                            Diversified Outsourcing Services                   50595.000000
                            Education                                          15585.000000
                            Financial Data Services                            13943.473684
                            Miscellaneous                                      12573.333333
                            Temporary Help                                     12004.000000
                            Waste Management                                   23839.800000
Chemicals                   Chemicals                                          15455.033333
Energy                      Energy                                              5005.142857
                            Mining, Crude-Oil Production                        5325.357143
                            Miscellaneous                                       6700.000000
                            Oil and Gas Equipment, Services                    25088.333333
                            Petroleum Refining                                 14404.705882
                            Pipelines                                           6011.750000
                            Utilities: Gas and Electric                        10249.487805
Engineering & Construction  Engineering, Construction                          26293.142857
                            Homebuilders                                        3217.000000
Financials                  Commercial Banks                                   54965.142857
                            Diversified Financials                             21940.933333
                            Insurance: Life, Health (Mutual)                    5880.100000
                            Insurance: Life, Health (stock)                    11235.166667
                            Insurance: Property and Casualty (Mutual)          19021.142857
                            Insurance: Property and Casualty (Stock)           28361.535714
                            Real estate                                        10705.266667
                            Securities                                          7940.333333
Food and Drug Stores        Food and Drug Stores                               93026.533333
Food, Beverages & Tobacco   Beverages                                          22123.000000
                            Food Consumer Products                             33271.950000
                                                                                  ...
Materials                   Metals                                             13825.642857
                            Miscellaneous                                         52.000000
                            Packaging, Containers                              20840.375000
Media                       Entertainment                                      21309.111111
                            Publishing, Printing                               23821.428571
Motor Vehicles & Parts      Motor Vehicles and Parts                           45106.666667
Retailing                   Automotive Retailing, Services                     17497.400000
                            General Merchandisers                             340810.000000
                            Specialty Retailers: Apparel                       42807.944444
                            Specialty Retailers: Other                         44619.333333
Technology                  Computer Peripherals                               43814.750000
                            Computer Software                                  27771.142857
                            Computers, Office Equipment                        66869.285714
                            Information Technology Services                    75818.384615
                            Internet Services and Retailing                    28723.666667
                            Network and Other Communications Equipment         21379.285714
                            Scientific,Photographic and Control Equipment      19291.750000
                            Semiconductors and Other Electronic Components     26065.391304
Telecommunications          Telecommunications                                 55497.866667
Transportation              Airlines                                           43511.222222
                            Mail, Package, and Freight Delivery               332137.500000
                            Miscellaneous                                       4200.000000
                            Railroads                                          24368.800000
                            Transportation Equipment                           11945.200000
                            Transportation and Logistics                       24938.200000
                            Trucking, Truck Leasing                            18939.555556
Wholesalers                 Miscellaneous                                       9200.000000
                            Wholesalers: Diversified                            9353.240000
                            Wholesalers: Electronics and Office Equipment      20832.625000
                            Wholesalers: Food and Grocery                      19317.500000
Name: Employees, Length: 79, dtype: float64

# THE .AGG() METHOD

In [19]:
fortune =pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby(by = ["Sector","Industry"])
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

# allows us to perform agg functions on our columns within dataframe

In [20]:
sectors["Employees"].mean()

Sector                      Industry
Aerospace & Defense         Aerospace and Defense                              48402.850000
Apparel                     Apparel                                            23093.133333
Business Services           Advertising, marketing                             62050.000000
                            Diversified Outsourcing Services                   50595.000000
                            Education                                          15585.000000
                            Financial Data Services                            13943.473684
                            Miscellaneous                                      12573.333333
                            Temporary Help                                     12004.000000
                            Waste Management                                   23839.800000
Chemicals                   Chemicals                                          15455.033333
Energy                      Energy                                              5005.142857
                            Mining, Crude-Oil Production                        5325.357143
                            Miscellaneous                                       6700.000000
                            Oil and Gas Equipment, Services                    25088.333333
                            Petroleum Refining                                 14404.705882
                            Pipelines                                           6011.750000
                            Utilities: Gas and Electric                        10249.487805
Engineering & Construction  Engineering, Construction                          26293.142857
                            Homebuilders                                        3217.000000
Financials                  Commercial Banks                                   54965.142857
                            Diversified Financials                             21940.933333
                            Insurance: Life, Health (Mutual)                    5880.100000
                            Insurance: Life, Health (stock)                    11235.166667
                            Insurance: Property and Casualty (Mutual)          19021.142857
                            Insurance: Property and Casualty (Stock)           28361.535714
                            Real estate                                        10705.266667
                            Securities                                          7940.333333
Food and Drug Stores        Food and Drug Stores                               93026.533333
Food, Beverages & Tobacco   Beverages                                          22123.000000
                            Food Consumer Products                             33271.950000
                                                                                  ...
Materials                   Metals                                             13825.642857
                            Miscellaneous                                         52.000000
                            Packaging, Containers                              20840.375000
Media                       Entertainment                                      21309.111111
                            Publishing, Printing                               23821.428571
Motor Vehicles & Parts      Motor Vehicles and Parts                           45106.666667
Retailing                   Automotive Retailing, Services                     17497.400000
                            General Merchandisers                             340810.000000
                            Specialty Retailers: Apparel                       42807.944444
                            Specialty Retailers: Other                         44619.333333
Technology                  Computer Peripherals                               43814.750000
                            Computer Software                                  27771.142857
                            Computers, Office Equipment                        66869.285714
                            Information Technology Services                    75818.384615
                            Internet Services and Retailing                    28723.666667
                            Network and Other Communications Equipment         21379.285714
                            Scientific,Photographic and Control Equipment      19291.750000
                            Semiconductors and Other Electronic Components     26065.391304
Telecommunications          Telecommunications                                 55497.866667
Transportation              Airlines                                           43511.222222
                            Mail, Package, and Freight Delivery               332137.500000
                            Miscellaneous                                       4200.000000
                            Railroads                                          24368.800000
                            Transportation Equipment                           11945.200000
                            Transportation and Logistics                       24938.200000
                            Trucking, Truck Leasing                            18939.555556
Wholesalers                 Miscellaneous                                       9200.000000
                            Wholesalers: Diversified                            9353.240000
                            Wholesalers: Electronics and Office Equipment      20832.625000
                            Wholesalers: Food and Grocery                      19317.500000
Name: Employees, Length: 79, dtype: float64

# with agg method u can apply agg function on multiple columns

In [25]:
sectors.agg({"Revenue":["size","sum","mean"],
        "Profits": "sum",
        "Employees" : "mean"})

                                                                          Revenue  \
                                                                             size
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                               20
Apparel                    Apparel                                             15
Business Services          Advertising, marketing                               2
                           Diversified Outsourcing Services                    14
                           Education                                            3
                           Financial Data Services                             19
                           Miscellaneous                                        3
                           Temporary Help                                       5
                           Waste Management                                     5
Chemicals                  Chemicals                                           30
Energy                     Energy                                              14
                           Mining, Crude-Oil Production                        28
                           Miscellaneous                                        1
                           Oil and Gas Equipment, Services                      9
                           Petroleum Refining                                  17
                           Pipelines                                           12
                           Utilities: Gas and Electric                         41
Engineering & Construction Engineering, Construction                           14
                           Homebuilders                                        12
Financials                 Commercial Banks                                    28
                           Diversified Financials                              15
                           Insurance: Life, Health (Mutual)                    10
                           Insurance: Life, Health (stock)                     18
                           Insurance: Property and Casualty (Mutual)            7
                           Insurance: Property and Casualty (Stock)            28
                           Real estate                                         15
                           Securities                                          18
Food and Drug Stores       Food and Drug Stores                                15
Food, Beverages & Tobacco  Beverages                                            9
                           Food Consumer Products                              20
...                                                                           ...
Materials                  Metals                                              14
                           Miscellaneous                                        1
                           Packaging, Containers                               16
Media                      Entertainment                                       18
                           Publishing, Printing                                 7
Motor Vehicles & Parts     Motor Vehicles and Parts                            24
Retailing                  Automotive Retailing, Services                      10
                           General Merchandisers                               10
                           Specialty Retailers: Apparel                        18
                           Specialty Retailers: Other                          42
Technology                 Computer Peripherals                                 4
                           Computer Software                                   14
                           Computers, Office Equipment                          7
                           Information Technology Services                     13
                           Internet Services and Retailing                     15
                           Network and Other Communications Equipment          14
                           Scientific,Photographic and Control Equipment       12
                           Semiconductors and Other Electronic Components      23
Telecommunications         Telecommunications                                  15
Transportation             Airlines                                             9
                           Mail, Package, and Freight Delivery                  2
                           Miscellaneous                                        1
                           Railroads                                            5
                           Transportation Equipment                             5
                           Transportation and Logistics                         5
                           Trucking, Truck Leasing                              9
Wholesalers                Miscellaneous                                        1
                           Wholesalers: Diversified                            25
                           Wholesalers: Electronics and Office Equipment        8
                           Wholesalers: Food and Grocery                        6

                                                                                   \
                                                                              sum
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                           357940
Apparel                    Apparel                                          95968
Business Services          Advertising, marketing                           22748
                           Diversified Outsourcing Services                 64829
                           Education                                         7485
                           Financial Data Services                         100778
                           Miscellaneous                                    11185
                           Temporary Help                                   34716
                           Waste Management                                 30454
Chemicals                  Chemicals                                       243897
Energy                     Energy                                           67749
                           Mining, Crude-Oil Production                    176435
                           Miscellaneous                                     3159
                           Oil and Gas Equipment, Services                  82827
                           Petroleum Refining                              705472
                           Pipelines                                       138756
                           Utilities: Gas and Electric                     343411
Engineering & Construction Engineering, Construction                        99774
                           Homebuilders                                     54209
Financials                 Commercial Banks                                623669
                           Diversified Financials                          327075
                           Insurance: Life, Health (Mutual)                181336
                           Insurance: Life, Health (stock)                 245551
                           Insurance: Property and Casualty (Mutual)       143682
                           Insurance: Property and Casualty (Stock)        548027
                           Real estate                                      62748
                           Securities                                       85071
Food and Drug Stores       Food and Drug Stores                            483769
Food, Beverages & Tobacco  Beverages                                        79396
                           Food Consumer Products                          238954
...                                                                           ...
Materials                  Metals                                           99925
                           Miscellaneous                                     6070
                           Packaging, Containers                           105965
Media                      Entertainment                                   186276
                           Publishing, Printing                             34488
Motor Vehicles & Parts     Motor Vehicles and Parts                        482540
Retailing                  Automotive Retailing, Services                  113823
                           General Merchandisers                           684320
                           Specialty Retailers: Apparel                    122975
                           Specialty Retailers: Other                      543958
Technology                 Computer Peripherals                             48950
                           Computer Software                               179112
                           Computers, Office Equipment                     353781
                           Information Technology Services                 166067
                           Internet Services and Retailing                 259136
                           Network and Other Communications Equipment      125697
                           Scientific,Photographic and Control Equipment    65832
                           Semiconductors and Other Electronic Components  179025
Telecommunications         Telecommunications                              461834
Transportation             Airlines                                        158948
                           Mail, Package, and Freight Delivery             105816
                           Miscellaneous                                     2148
                           Railroads                                        48554
                           Transportation Equipment                         23855
                           Transportation and Logistics                     33237
                           Trucking, Truck Leasing                          35950
Wholesalers                Miscellaneous                                     8982
                           Wholesalers: Diversified                        176138
                           Wholesalers: Electronics and Office Equipment   147906
                           Wholesalers: Food and Grocery                   111774

                                                                                         \
                                                                                   mean
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                           17897.000000
Apparel                    Apparel                                          6397.866667
Business Services          Advertising, marketing                          11374.000000
                           Diversified Outsourcing Services                 4630.642857
                           Education                                        2495.000000
                           Financial Data Services                          5304.105263
                           Miscellaneous                                    3728.333333
                           Temporary Help                                   6943.200000
                           Waste Management                                 6090.800000
Chemicals                  Chemicals                                        8129.900000
Energy                     Energy                                           4839.214286
                           Mining, Crude-Oil Production                     6301.250000
                           Miscellaneous                                    3159.000000
                           Oil and Gas Equipment, Services                  9203.000000
                           Petroleum Refining                              41498.352941
                           Pipelines                                       11563.000000
                           Utilities: Gas and Electric                      8375.878049
Engineering & Construction Engineering, Construction                        7126.714286
                           Homebuilders                                     4517.416667
Financials                 Commercial Banks                                22273.892857
                           Diversified Financials                          21805.000000
                           Insurance: Life, Health (Mutual)                18133.600000
                           Insurance: Life, Health (stock)                 13641.722222
                           Insurance: Property and Casualty (Mutual)       20526.000000
                           Insurance: Property and Casualty (Stock)        19572.392857
                           Real estate                                      4183.200000
                           Securities                                       4726.166667
Food and Drug Stores       Food and Drug Stores                            32251.266667
Food, Beverages & Tobacco  Beverages                                        8821.777778
                           Food Consumer Products                          11947.700000
...                                                                                 ...
Materials                  Metals                                           7137.500000
                           Miscellaneous                                    6070.000000
                           Packaging, Containers                            6622.812500
Media                      Entertainment                                   10348.666667
                           Publishing, Printing                             4926.857143
Motor Vehicles & Parts     Motor Vehicles and Parts                        20105.833333
Retailing                  Automotive Retailing, Services                  11382.300000
                           General Merchandisers                           68432.000000
                           Specialty Retailers: Apparel                     6831.944444
                           Specialty Retailers: Other                      12951.380952
Technology                 Computer Peripherals                            12237.500000
                           Computer Software                               12793.714286
                           Computers, Office Equipment                     50540.142857
                           Information Technology Services                 12774.384615
                           Internet Services and Retailing                 17275.733333
                           Network and Other Communications Equipment       8978.357143
                           Scientific,Photographic and Control Equipment    5486.000000
                           Semiconductors and Other Electronic Components   7783.695652
Telecommunications         Telecommunications                              30788.933333
Transportation             Airlines                                        17660.888889
                           Mail, Package, and Freight Delivery             52908.000000
                           Miscellaneous                                    2148.000000
                           Railroads                                        9710.800000
                           Transportation Equipment                         4771.000000
                           Transportation and Logistics                     6647.400000
                           Trucking, Truck Leasing                          3994.444444
Wholesalers                Miscellaneous                                    8982.000000
                           Wholesalers: Diversified                         7045.520000
                           Wholesalers: Electronics and Office Equipment   18488.250000
                           Wholesalers: Food and Grocery                   18629.000000

                                                                          Profits  \
                                                                              sum
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            28742
Apparel                    Apparel                                           8236
Business Services          Advertising, marketing                            1549
                           Diversified Outsourcing Services                  4305
                           Education                                           69
                           Financial Data Services                          17456
                           Miscellaneous                                     2130
                           Temporary Help                                    1000
                           Waste Management                                  1718
Chemicals                  Chemicals                                        22628
Energy                     Energy                                          -13038
                           Mining, Crude-Oil Production                   -124555
                           Miscellaneous                                      476
                           Oil and Gas Equipment, Services                  -4047
                           Petroleum Refining                               31888
                           Pipelines                                         5814
                           Utilities: Gas and Electric                      30015
Engineering & Construction Engineering, Construction                         1765
                           Homebuilders                                      3539
Financials                 Commercial Banks                                129760
                           Diversified Financials                           28548
                           Insurance: Life, Health (Mutual)                  5601
                           Insurance: Life, Health (stock)                  19731
                           Insurance: Property and Casualty (Mutual)         8031
                           Insurance: Property and Casualty (Stock)         44803
                           Real estate                                       9480
                           Securities                                       14255
Food and Drug Stores       Food and Drug Stores                             16759
Food, Beverages & Tobacco  Beverages                                        11698
                           Food Consumer Products                           19263
...                                                                           ...
Materials                  Metals                                           -2241
                           Miscellaneous                                        7
                           Packaging, Containers                             4445
Media                      Entertainment                                    25686
                           Publishing, Printing                             -1339
Motor Vehicles & Parts     Motor Vehicles and Parts                         25898
Retailing                  Automotive Retailing, Services                    2550
                           General Merchandisers                            20137
                           Specialty Retailers: Apparel                      4583
                           Specialty Retailers: Other                       20560
Technology                 Computer Peripherals                              3975
                           Computer Software                                26457
                           Computers, Office Equipment                      58433
                           Information Technology Services                  16402
                           Internet Services and Retailing                  22232

In [23]:
sectors.agg({"size","sum","mean"})

                                                                          Revenue  \
                                                                              sum
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                           357940
Apparel                    Apparel                                          95968
Business Services          Advertising, marketing                           22748
                           Diversified Outsourcing Services                 64829
                           Education                                         7485
                           Financial Data Services                         100778
                           Miscellaneous                                    11185
                           Temporary Help                                   34716
                           Waste Management                                 30454
Chemicals                  Chemicals                                       243897
Energy                     Energy                                           67749
                           Mining, Crude-Oil Production                    176435
                           Miscellaneous                                     3159
                           Oil and Gas Equipment, Services                  82827
                           Petroleum Refining                              705472
                           Pipelines                                       138756
                           Utilities: Gas and Electric                     343411
Engineering & Construction Engineering, Construction                        99774
                           Homebuilders                                     54209
Financials                 Commercial Banks                                623669
                           Diversified Financials                          327075
                           Insurance: Life, Health (Mutual)                181336
                           Insurance: Life, Health (stock)                 245551
                           Insurance: Property and Casualty (Mutual)       143682
                           Insurance: Property and Casualty (Stock)        548027
                           Real estate                                      62748
                           Securities                                       85071
Food and Drug Stores       Food and Drug Stores                            483769
Food, Beverages & Tobacco  Beverages                                        79396
                           Food Consumer Products                          238954
...                                                                           ...
Materials                  Metals                                           99925
                           Miscellaneous                                     6070
                           Packaging, Containers                           105965
Media                      Entertainment                                   186276
                           Publishing, Printing                             34488
Motor Vehicles & Parts     Motor Vehicles and Parts                        482540
Retailing                  Automotive Retailing, Services                  113823
                           General Merchandisers                           684320
                           Specialty Retailers: Apparel                    122975
                           Specialty Retailers: Other                      543958
Technology                 Computer Peripherals                             48950
                           Computer Software                               179112
                           Computers, Office Equipment                     353781
                           Information Technology Services                 166067
                           Internet Services and Retailing                 259136
                           Network and Other Communications Equipment      125697
                           Scientific,Photographic and Control Equipment    65832
                           Semiconductors and Other Electronic Components  179025
Telecommunications         Telecommunications                              461834
Transportation             Airlines                                        158948
                           Mail, Package, and Freight Delivery             105816
                           Miscellaneous                                     2148
                           Railroads                                        48554
                           Transportation Equipment                         23855
                           Transportation and Logistics                     33237
                           Trucking, Truck Leasing                          35950
Wholesalers                Miscellaneous                                     8982
                           Wholesalers: Diversified                        176138
                           Wholesalers: Electronics and Office Equipment   147906
                           Wholesalers: Food and Grocery                   111774

                                                                                \
                                                                          size
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            20
Apparel                    Apparel                                          15
Business Services          Advertising, marketing                            2
                           Diversified Outsourcing Services                 14
                           Education                                         3
                           Financial Data Services                          19
                           Miscellaneous                                     3
                           Temporary Help                                    5
                           Waste Management                                  5
Chemicals                  Chemicals                                        30
Energy                     Energy                                           14
                           Mining, Crude-Oil Production                     28
                           Miscellaneous                                     1
                           Oil and Gas Equipment, Services                   9
                           Petroleum Refining                               17
                           Pipelines                                        12
                           Utilities: Gas and Electric                      41
Engineering & Construction Engineering, Construction                        14
                           Homebuilders                                     12
Financials                 Commercial Banks                                 28
                           Diversified Financials                           15
                           Insurance: Life, Health (Mutual)                 10
                           Insurance: Life, Health (stock)                  18
                           Insurance: Property and Casualty (Mutual)         7
                           Insurance: Property and Casualty (Stock)         28
                           Real estate                                      15
                           Securities                                       18
Food and Drug Stores       Food and Drug Stores                             15
Food, Beverages & Tobacco  Beverages                                         9
                           Food Consumer Products                           20
...                                                                        ...
Materials                  Metals                                           14
                           Miscellaneous                                     1
                           Packaging, Containers                            16
Media                      Entertainment                                    18
                           Publishing, Printing                              7
Motor Vehicles & Parts     Motor Vehicles and Parts                         24
Retailing                  Automotive Retailing, Services                   10
                           General Merchandisers                            10
                           Specialty Retailers: Apparel                     18
                           Specialty Retailers: Other                       42
Technology                 Computer Peripherals                              4
                           Computer Software                                14
                           Computers, Office Equipment                       7
                           Information Technology Services                  13
                           Internet Services and Retailing                  15
                           Network and Other Communications Equipment       14
                           Scientific,Photographic and Control Equipment    12
                           Semiconductors and Other Electronic Components   23
Telecommunications         Telecommunications                               15
Transportation             Airlines                                          9
                           Mail, Package, and Freight Delivery               2
                           Miscellaneous                                     1
                           Railroads                                         5
                           Transportation Equipment                          5
                           Transportation and Logistics                      5
                           Trucking, Truck Leasing                           9
Wholesalers                Miscellaneous                                     1
                           Wholesalers: Diversified                         25
                           Wholesalers: Electronics and Office Equipment     8
                           Wholesalers: Food and Grocery                     6

                                                                                         \
                                                                                   mean
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                           17897.000000
Apparel                    Apparel                                          6397.866667
Business Services          Advertising, marketing                          11374.000000
                           Diversified Outsourcing Services                 4630.642857
                           Education                                        2495.000000
                           Financial Data Services                          5304.105263
                           Miscellaneous                                    3728.333333
                           Temporary Help                                   6943.200000
                           Waste Management                                 6090.800000
Chemicals                  Chemicals                                        8129.900000
Energy                     Energy                                           4839.214286
                           Mining, Crude-Oil Production                     6301.250000
                           Miscellaneous                                    3159.000000
                           Oil and Gas Equipment, Services                  9203.000000
                           Petroleum Refining                              41498.352941
                           Pipelines                                       11563.000000
                           Utilities: Gas and Electric                      8375.878049
Engineering & Construction Engineering, Construction                        7126.714286
                           Homebuilders                                     4517.416667
Financials                 Commercial Banks                                22273.892857
                           Diversified Financials                          21805.000000
                           Insurance: Life, Health (Mutual)                18133.600000
                           Insurance: Life, Health (stock)                 13641.722222
                           Insurance: Property and Casualty (Mutual)       20526.000000
                           Insurance: Property and Casualty (Stock)        19572.392857
                           Real estate                                      4183.200000
                           Securities                                       4726.166667
Food and Drug Stores       Food and Drug Stores                            32251.266667
Food, Beverages & Tobacco  Beverages                                        8821.777778
                           Food Consumer Products                          11947.700000
...                                                                                 ...
Materials                  Metals                                           7137.500000
                           Miscellaneous                                    6070.000000
                           Packaging, Containers                            6622.812500
Media                      Entertainment                                   10348.666667
                           Publishing, Printing                             4926.857143
Motor Vehicles & Parts     Motor Vehicles and Parts                        20105.833333
Retailing                  Automotive Retailing, Services                  11382.300000
                           General Merchandisers                           68432.000000
                           Specialty Retailers: Apparel                     6831.944444
                           Specialty Retailers: Other                      12951.380952
Technology                 Computer Peripherals                            12237.500000
                           Computer Software                               12793.714286
                           Computers, Office Equipment                     50540.142857
                           Information Technology Services                 12774.384615
                           Internet Services and Retailing                 17275.733333
                           Network and Other Communications Equipment       8978.357143
                           Scientific,Photographic and Control Equipment    5486.000000
                           Semiconductors and Other Electronic Components   7783.695652
Telecommunications         Telecommunications                              30788.933333
Transportation             Airlines                                        17660.888889
                           Mail, Package, and Freight Delivery             52908.000000
                           Miscellaneous                                    2148.000000
                           Railroads                                        9710.800000
                           Transportation Equipment                         4771.000000
                           Transportation and Logistics                     6647.400000
                           Trucking, Truck Leasing                          3994.444444
Wholesalers                Miscellaneous                                    8982.000000
                           Wholesalers: Diversified                         7045.520000
                           Wholesalers: Electronics and Office Equipment   18488.250000
                           Wholesalers: Food and Grocery                   18629.000000

                                                                          Profits  \
                                                                              sum
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            28742
Apparel                    Apparel                                           8236
Business Services          Advertising, marketing                            1549
                           Diversified Outsourcing Services                  4305
                           Education                                           69
                           Financial Data Services                          17456
                           Miscellaneous                                     2130
                           Temporary Help                                    1000
                           Waste Management                                  1718
Chemicals                  Chemicals                                        22628
Energy                     Energy                                          -13038
                           Mining, Crude-Oil Production                   -124555
                           Miscellaneous                                      476
                           Oil and Gas Equipment, Services                  -4047
                           Petroleum Refining                               31888
                           Pipelines                                         5814
                           Utilities: Gas and Electric                      30015
Engineering & Construction Engineering, Construction                         1765
                           Homebuilders                                      3539
Financials                 Commercial Banks                                129760
                           Diversified Financials                           28548
                           Insurance: Life, Health (Mutual)                  5601
                           Insurance: Life, Health (stock)                  19731
                           Insurance: Property and Casualty (Mutual)         8031
                           Insurance: Property and Casualty (Stock)         44803
                           Real estate                                       9480
                           Securities                                       14255
Food and Drug Stores       Food and Drug Stores                             16759
Food, Beverages & Tobacco  Beverages                                        11698
                           Food Consumer Products                           19263
...                                                                           ...
Materials                  Metals                                           -2241
                           Miscellaneous                                        7
                           Packaging, Containers                             4445
Media                      Entertainment                                    25686
                           Publishing, Printing                             -1339
Motor Vehicles & Parts     Motor Vehicles and Parts                         25898
Retailing                  Automotive Retailing, Services                    2550
                           General Merchandisers                            20137
                           Specialty Retailers: Apparel                      4583
                           Specialty Retailers: Other                       20560
Technology                 Computer Peripherals                              3975
                           Computer Software                                26457
                           Computers, Office Equipment                      58433
                           Information Technology Services                  16402
                           Internet Services and Retailing                  22232
                           Network and Other Communications Equipment       18907
                           Scientific,Photographic and Control Equipment     9346

# ITERATING THROUGH GROUPS

In [55]:
fortune =pd.read_csv("fortune1000.csv",index_col="Rank")
sectors = fortune.groupby(by = ["Sector","Industry"])
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

# want to extract highest profit or highest revenue

In [56]:
sectors["Profits"].max()

Sector                      Industry
Aerospace & Defense         Aerospace and Defense                              7608
Apparel                     Apparel                                            3273
Business Services           Advertising, marketing                             1094
                            Diversified Outsourcing Services                   1453
                            Education                                           140
                            Financial Data Services                            6328
                            Miscellaneous                                      1311
                            Temporary Help                                      419
                            Waste Management                                    753
Chemicals                   Chemicals                                          7685
Energy                      Energy                                              546
                            Mining, Crude-Oil Production                        941
                            Miscellaneous                                       476
                            Oil and Gas Equipment, Services                     501
                            Petroleum Refining                                16150
                            Pipelines                                          2521
                            Utilities: Gas and Electric                        2816
Engineering & Construction  Engineering, Construction                           413
                            Homebuilders                                        803
Financials                  Commercial Banks                                  24442
                            Diversified Financials                            10954
                            Insurance: Life, Health (Mutual)                   1425
                            Insurance: Life, Health (stock)                    5642
                            Insurance: Property and Casualty (Mutual)          6229
                            Insurance: Property and Casualty (Stock)          24083
                            Real estate                                        1828
                            Securities                                         3345
Food and Drug Stores        Food and Drug Stores                               5237
Food, Beverages & Tobacco   Beverages                                          7351
                            Food Consumer Products                             7267
                                                                              ...
Materials                   Metals                                              358
                            Miscellaneous                                         7
                            Packaging, Containers                               938
Media                       Entertainment                                      8382
                            Publishing, Printing                                151
Motor Vehicles & Parts      Motor Vehicles and Parts                           9687
Retailing                   Automotive Retailing, Services                      597
                            General Merchandisers                             14694
                            Specialty Retailers: Apparel                       2278
                            Specialty Retailers: Other                         7009
Technology                  Computer Peripherals                               1990
                            Computer Software                                 12193
                            Computers, Office Equipment                       53394
                            Information Technology Services                   13190
                            Internet Services and Retailing                   16348
                            Network and Other Communications Equipment         8981
                            Scientific,Photographic and Control Equipment      3357
                            Semiconductors and Other Electronic Components    11420
Telecommunications          Telecommunications                                17879
Transportation              Airlines                                           7610
                            Mail, Package, and Freight Delivery                4844
                            Miscellaneous                                       227
                            Railroads                                          4772
                            Transportation Equipment                            797
                            Transportation and Logistics                        510
                            Trucking, Truck Leasing                             427
Wholesalers                 Miscellaneous                                        17
                            Wholesalers: Diversified                           1472
                            Wholesalers: Electronics and Office Equipment       572
                            Wholesalers: Food and Grocery                       687
Name: Profits, Length: 79, dtype: int64

# we need to iterate as we need multiple things done

In [57]:
df = pd.DataFrame(columns=fortune.columns)

In [58]:
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

# next step - looping through all our groups and getting highest revenue

# you always have to provide two variable names each time you iterate over a group by object

# 1st variable - to represent the group
# 2nd variable - to represent the actual dataframe that is STORED WITHIN THAT GROUPING

# nlargest- we want to specify the number of values we want, in this case only the top value, then the second argument you specify which column

# data is temporary VARIABLE name -for each one of our 21 data frames

# append will just add everything together

In [59]:
for sector, data in sectors:
    
    highest_revenue_company_in_group = data.nlargest(1,"Revenue")
    df = df.append(highest_revenue_company_in_group)

In [60]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
186,Omnicom Group,Business Services,"Advertising, marketing","New York, NY",15134,1094,74900
199,Aramark,Business Services,Diversified Outsourcing Services,"Philadelphia, PA",14329,236,216500
737,Graham Holdings,Business Services,Education,"Arlington, VA",2984,-101,11585
204,Visa,Business Services,Financial Data Services,"Foster City, CA",13880,6328,11300
440,United Rentals,Business Services,Miscellaneous,"Stamford, CT",5817,585,12700
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
221,Waste Management,Business Services,Waste Management,"Houston, TX",12961,753,40600
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
193,NRG Energy,Energy,Energy,"Princeton, NJ",14674,-6382,10468
90,ConocoPhillips,Energy,"Mining, Crude-Oil Production","Houston, TX",30935,-4428,15900
696,American Water Works,Energy,Miscellaneous,"Voorhees, NJ",3159,476,6700
117,Halliburton,Energy,"Oil and Gas Equipment, Services","Houston, TX",23633,-671,65000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
65,Energy Transfer Equity,Energy,Pipelines,"Dallas, TX",42126,1189,30078
95,Exelon,Energy,Utilities: Gas and Electric,"Chicago, IL",29447,2269,29762
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
260,D.R. Horton,Engineering & Construction,Homebuilders,"Fort Worth, TX",10824,751,6230
23,J.P. Morgan Chase,Financials,Commercial Banks,"New York, NY",101006,24442,234598
16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
61,New York Life Insurance,Financials,"Insurance: Life, Health (Mutual)","New York, NY",45891,257,11463
40,MetLife,Financials,"Insurance: Life, Health (stock)","New York, NY",69951,5310,69000
35,State Farm Insurance Cos.,Financials,Insurance: Property and Casualty (Mutual),"Bloomington, IL",75697,6229,70425
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
259,CBRE Group,Financials,Real estate,"Los Angeles, CA",10856,547,70000
250,BlackRock,Financials,Securities,"New York, NY",11401,3345,13000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
62,Coca-Cola,"Food, Beverages & Tobacco",Beverages,"Atlanta, GA",44294,7351,123200
44,PepsiCo,"Food, Beverages & Tobacco",Food Consumer Products,"Purchase, NY",63056,5452,263000
...,...,...,...,...,...,...,...
126,Alcoa,Materials,Metals,"New York, NY",22534,-322,60000
426,A-Mark Precious Metals,Materials,Miscellaneous,"Santa Monica, CA",6070,7,52
127,International Paper,Materials,"Packaging, Containers","Memphis, TN",22365,938,56000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
255,R.R. Donnelley & Sons,Media,"Publishing, Printing","Chicago, IL",11257,151,68400
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
136,AutoNation,Retailing,"Automotive Retailing, Services","Fort Lauderdale, FL",20862,443,26000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
89,TJX,Retailing,Specialty Retailers: Apparel,"Framingham, MA",30945,2278,216000
15,Costco,Retailing,Specialty Retailers: Other,"Issaquah, WA",116199,2377,161000
113,EMC,Technology,Computer Peripherals,"Hopkinton, MA",24704,1990,72000
25,Microsoft,Technology,Computer Software,"Redmond, WA",93580,12193,118000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
31,IBM,Technology,Information Technology Services,"Armonk, NY",82461,13190,411798
18,Amazon.com,Technology,Internet Services and Retailing,"Seattle, WA",107006,596,230800
54,Cisco Systems,Technology,Network and Other Communications Equipment,"San Jose, CA",49161,8981,71833
133,Danaher,Technology,"Scientific,Photographic and Control Equipment","Washington, DC",20909,3357,81000
51,Intel,Technology,Semiconductors and Other Electronic Components,"Santa Clara, CA",55355,11420,107300
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
67,American Airlines Group,Transportation,Airlines,"Fort Worth, TX",40990,7610,118500
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
930,Kirby,Transportation,Miscellaneous,"Houston, TX",2148,227,4200
129,Union Pacific,Transportation,Railroads,"Omaha, NE",21813,4772,47457
407,Trinity Industries,Transportation,Transportation Equipment,"Dallas, TX",6393,797,22030
208,C.H. Robinson Worldwide,Transportation,Transportation and Logistics,"Eden Prairie, MN",13476,510,13159
395,Ryder System,Transportation,"Trucking, Truck Leasing","Miami, FL",6572,305,33100
315,Univar,Wholesalers,Miscellaneous,"Downers Grove, IL",8982,17,9200
92,World Fuel Services,Wholesalers,Wholesalers: Diversified,"Miami, FL",30380,187,4700
64,Ingram Micro,Wholesalers,Wholesalers: Electronics and Office Equipment,"Irvine, CA",43026,215,27700
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

# the above dataframe shows the highest revenue making 21 companies

# NEXT EXAMPLE : CITY BASED ANALYSIS HIGHEST REVENUE rather than sector based

In [66]:
cities = fortune.groupby(by = "Location")
cities
df = pd.DataFrame(columns=fortune.columns)
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

In [67]:
for city,data in cities:
    highest_profit_city = data.nlargest(1,"Profits")
    df = df.append(highest_profit_city)

In [68]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
138,Abbott Laboratories,Health Care,Medical Products and Equipment,"Abbott Park, IL",20661,4423,74000
188,FirstEnergy,Energy,Utilities: Gas and Electric,"Akron, OH",15026,578,15781
288,Air Products & Chemicals,Chemicals,Chemicals,"Allentown, PA",9895,1278,19550
830,Benchmark Electronics,Technology,Semiconductors and Other Electronic Components,"Angleton, TX",2541,95,10500
374,Casey’s General Stores,Retailing,Specialty Retailers: Other,"Ankeny, IA",7052,181,22408
915,Domino’s Pizza,"Hotels, Resturants & Leisure",Food Services,"Ann Arbor, MI",2217,193,11900
596,Colfax,Industrials,Industrial Machinery,"Annapolis Junction, MD",3967,168,17087
215,Land O’Lakes,"Food, Beverages & Tobacco",Food Consumer Products,"Arden Hills, MN",13161,308,10000
626,Towers Watson,Business Services,Diversified Outsourcing Services,"Arlington, VA",3645,385,16300
31,IBM,Technology,Information Technology Services,"Armonk, NY",82461,13190,411798
62,Coca-Cola,"Food, Beverages & Tobacco",Beverages,"Atlanta, GA",44294,7351,123200
339,BorgWarner,Motor Vehicles & Parts,Motor Vehicles and Parts,"Auburn Hills, MI",8023,610,30000
304,Hormel Foods,"Food, Beverages & Tobacco",Food Consumer Products,"Austin, MN",9264,686,20700
181,Whole Foods Market,Food and Drug Stores,Food and Drug Stores,"Austin, TX",15389,536,76300
668,PolyOne,Chemicals,Chemicals,"Avon Lake, OH",3378,145,6900
573,T. Rowe Price,Financials,Securities,"Baltimore, MD",4201,1223,5999
420,Baxalta,Health Care,Pharmaceuticals,"Bannockburn, IL",6149,956,17000
624,Albemarle,Chemicals,Chemicals,"Baton Rouge, LA",3651,335,6963
207,Kellogg,"Food, Beverages & Tobacco",Food Consumer Products,"Battle Creek, MI",13525,614,33577
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
147,Paccar,Motor Vehicles & Parts,Motor Vehicles and Parts,"Bellevue, WA",19115,1604,23000
645,Regal Beloit,Industrials,"Electronics, Electrical Equip.","Beloit, WI",3510,143,26200
134,Whirlpool,Industrials,"Electronics, Electrical Equip.","Benton Harbor, MI",20891,783,97000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
594,Ametek,Technology,"Scientific,Photographic and Control Equipment","Berwyn, PA",3974,591,15400
60,Lockheed Martin,Aerospace & Defense,Aerospace and Defense,"Bethesda, MD",46132,3605,126000
399,Cablevision Systems,Telecommunications,Telecommunications,"Bethpage, NY",6510,175,13549
366,Live Nation Entertainment,Media,Entertainment,"Beverly Hills, CA",7246,-33,12200
453,Regions Financial,Financials,Commercial Banks,"Birmingham, AL",5674,1062,23916
558,MDU Resources Group,Energy,Energy,"Bismarck, ND",4376,-622,8689
...,...,...,...,...,...,...,...
120,Raytheon,Aerospace & Defense,Aerospace and Defense,"Waltham, MA",23247,2074,61000
850,United Refining,Energy,Petroleum Refining,"Warren, PA",2470,82,2997
431,Zimmer Biomet Holdings,Health Care,Medical Products and Equipment,"Warsaw, IN",5998,147,17500
16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
542,Keurig Green Mountain,"Food, Beverages & Tobacco",Beverages,"Waterbury, VT",4520,498,6000
898,MPM Holdings,Chemicals,Chemicals,"Waterford, NY",2289,-83,5000
874,Granite Construction,Engineering & Construction,"Engineering, Construction","Watsonville, CA",2371,61,3200
1000,Briggs & Stratton,Industrials,Industrial Machinery,"Wauwatosa, WI",1895,46,5480
240,Toys “R” Us,Retailing,Specialty Retailers: Other,"Wayne, NJ",11802,-130,62000
785,B/E Aerospace,Aerospace & Defense,Aerospace and Defense,"Wellington, FL",2730,286,10057
383,AK Steel Holding,Materials,Metals,"West Chester, OH",6693,-509,8500
848,Affiliated Managers Group,Financials,Securities,"West Palm Beach, FL",2485,516,3200
996,New York Community Bancorp,Financials,Commercial Banks,"Westbury, NY",1902,-47,3448
456,Ingredion,"Food, Beverages & Tobacco",Food Production,"Westchester, IL",5621,402,11500
439,TravelCenters of America,Retailing,Specialty Retailers: Other,"Westlake, OH",5851,28,18450
396,Terex,Industrials,Construction and Farm Machinery,"Westport, CT",6543,146,20400
847,ITT,Industrials,Industrial Machinery,"White Plains, NY",2486,352,9700
389,Spirit AeroSystems Holdings,Aerospace & Defense,Aerospace and Defense,"Wichita, KS",6644,789,15200
849,Tops Holding,Food and Drug Stores,Food and Drug Stores,"Williamsville, NY",2472,-62,14800
674,Westinghouse Air Brake Technologies,Industrials,Industrial Machinery,"Wilmerding, PA",3308,399,13000
101,DuPont,Chemicals,Chemicals,"Wilmington, DE",27940,1953,52000
607,Fastenal,Retailing,Specialty Retailers: Other,"Winona, MN",3869,516,20746
266,Reynolds American,"Food, Beverages & Tobacco",Tobacco,"Winston-Salem, NC",10675,3253,5650
678,Skyworks Solutions,Technology,Semiconductors and Other Electronic Components,"Woburn, MA",3258,798,6700
172,Health Net,Health Care,Health Care: Insurance and Managed Care,"Woodland Hills, CA",16244,186,8584
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
506,Hanover Insurance Group,Financials,Insurance: Property and Casualty (Stock),"Worcester, MA",5034,332,4800
911,Carpenter Technology,Materials,Metals,"Wyomissing, PA",2227,59,4900
799,Dentsply Sirona,Health Care,Medical Products and Equipment,"York, PA",2674,251,11400
932,Herman Miller,Household Products,"Home Equipment, Furnishings","Zeeland, MI",2142,98,7510